/*****************************************************************************
 *                      Ada_to_C_Cpp_Translator
 *****************************************************************************
 * Adatoccpptranslator is a free software which convert Ada code to C/C++ 
 * source code
 * Copyright (C) 2004 Julien THEVENON
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for 
 * more details.
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * For further informations : adatoccpptranslator@free.fr
 * 
 * Description: translator
 *
 * $Log: translator.h,v $
 * Revision 1.4  2005/03/24 19:11:02  quicky2000
 * Update to correct bad include files names
 *
 * Revision 1.3  2005/03/16 18:36:45  quicky2000
 * Update for code maintenance
 *
 * Revision 1.2  2005/03/04 19:36:00  quicky2000
 * Update of path of include files due to changes in source orgnaisation
 *
 * Revision 1.1.1.1  2005/03/01 22:20:55  quicky2000
 * Initial import
 *
 *
 *****************************************************************************/
#ifndef TRANSLATOR_H
#define TRANSLATOR_H

#include "../src/Tools/configuration.h"
#include "../src/Tools/command_argument.h"
#include "../src/Tools/file_management.h"
#include "../src/Tools/list.h"
#include "../src/Tools/tree.h"

#include "../src/Stage_2/table_symbol_creation.h"
#include "../src/Stage_3/code_generation.h"
#include "../src/Stage_3/tree_translation.h"

/***********************************/
/* Extern declarations from parser */
/***********************************/
// yyparse function is defined in syntax.y
extern void yyparse(void);

//nl variable is declared in lexico.l
//it contains the line number of token find by flex
extern int g_LineNumber;

// mon yyval is declared in syntax.y file
// it references the tree generated by bison during syntax analysis
extern tree* myYyval;

/********************/
/* Global variables */
/********************/
char g_BoolSyntaxError = 0;
file *g_CurrentFile = NULL;
configuration *g_Config = new configuration();

/*************************/
/* Subprogs declarations */
/*************************/
int main(int argc, char** argv);

#endif
